<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/** @var \JustBetter\Sentry\Block\SentryScript $block */
if (!$block->canUseScriptTag($block->getNameInLayout())) {
    return;
}

$bundleFile = 'bundle';

if ($block->isTracingEnabled()) {
    $bundleFile .= '.tracing';
}

if ($block->useSessionReplay()) {
    $bundleFile .= '.replay';
}

$debugEnabled = $block->isDebuggingEnabled();

$bundleFile .= $debugEnabled ? '.js' : '.min.js';

$remoteFile = sprintf(
    'https://browser.sentry-cdn.com/%s/%s',
    $block->escapeHtmlAttr($block->getJsSdkVersion()),
    $bundleFile
);

// NIMA CHANGES
$remoteFileCaptureConsole = sprintf(
    'https://browser.sentry-cdn.com/%s/captureconsole.min.js',
    $block->escapeHtmlAttr($block->getJsSdkVersion())
);

$replaySessionRate = $block->getReplaySessionSampleRate();
$replayErrorRate = $block->getReplayErrorSampleRate();

// NIMA CHANGES - allow to fully log certain important uris
$replayOnlyUrls = $block->getSessionReplayOnlyUrls();

$requestUri = $_SERVER['REQUEST_URI'] ?? null;
$logAllReplays = false;

if ($requestUri && $replayOnlyUrls) {
    foreach ($replayOnlyUrls as $uri) {
        if (substr($requestUri, 0, strlen($uri)) == $uri) {
            $logAllReplays = true;
            $replaySessionRate = $replayErrorRate = '1';
            break;
        }
        unset($uri);
    }
}

?>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Promise" crossorigin></script>
<script src="<?= /** @noEscape */
$remoteFile ?>" crossorigin="anonymous"></script>
<script src="<?= /** @noEscape */
$remoteFileCaptureConsole ?>" crossorigin="anonymous"></script>
<script>
    Sentry.init({
        dsn: '<?= $block->escapeUrl(trim($block->getDSN())) ?>',
        <?php if ($debugEnabled): ?>
        debug: true,
        send_default_pii: true,
        <?php endif ?>
        release: '<?= $block->escapeHtml(trim($block->getVersion())) ?>',
        environment: '<?= $block->escapeHtml(trim($block->getEnvironment())) ?>',
        integrations: [
            new Sentry.Integrations.CaptureConsole({levels: ['error']}),
            <?php if ($block->isTracingEnabled()): ?>
            new Sentry.BrowserTracing(),
            <?php endif ?>
            <?php if ($block->useSessionReplay()): ?>
            new Sentry.Replay({
                blockAllMedia: <?= $block->escapeHtml($block->getReplayBlockMedia() ? 'true' : 'false') ?>,
                maskAllText: <?= $block->escapeHtml($block->getReplayMaskText() ? 'true' : 'false') ?>,
                networkDetailAllowUrls: [window.location.origin],
            })
            <?php endif ?>
        ],
        <?php if ($block->isTracingEnabled()): ?>
        tracesSampleRate: <?= $block->escapeHtml($block->getTracingSampleRate()) ?>,
        <?php endif ?>
        <?php if ($logAllReplays || $block->useSessionReplay()): ?>
        replaysSessionSampleRate: <?= $block->escapeHtml($replaySessionRate) ?>,
        replaysOnErrorSampleRate: <?= $block->escapeHtml($replayErrorRate) ?>,
        <?php endif ?>
        <?php if ($block->stripStaticContentVersion() || $block->stripStoreCode()): ?>
        beforeSend: function (event) {
            event.exception.values.map(function (value) {
                if (value.stacktrace === undefined || !value.stacktrace) {
                    return value;
                }

                <?php if ($block->stripStaticContentVersion()): ?>
                value.stacktrace.frames.map(function (frame) {
                    frame.filename = frame.filename.replace(/version[0-9]{10}\//, '');
                    return frame;
                });
                <?php endif; ?>

                <?php if ($block->stripStoreCode()): ?>
                value.stacktrace.frames.map(function (frame) {
                    <?php // phpcs:disable Generic.Files.LineLength ?>
                    frame.filename = frame.filename.replace('/<?= $block->escapeHtml($block->getStoreCode()); ?>/', '/');
                    <?php // phpcs:enable Generic.Files.LineLength ?>
                    return frame;
                });
                <?php endif; ?>

                return value;
            });
            return event;
        }
        <?php endif; ?>
    });
</script>
